#define STARTPRGM 1
#define LT 2
#define LE 3
#define EQ 4
#define NE 5
#define GT 6
#define GE 7
#define IF 8
#define THEN 9
#define ELIF 10
#define ELSE 11
#define IDENTIFIER 12
#define NUM 13
#define ARITHMOP 14
#define BEGINGS 15
#define ENDGS 16
#define WHILE 17
#define DO 18
#define COMMENT 19
#define ASSIGNMENT 20
#define FUNCTION 21
#define WRITE 22

